package com.space.extended.basicblocks;

import com.space.extended.NameUtils;
import com.space.extended.SpaceExtendedMain;
import com.space.extended.basicblocks.BlockMetalFrameCatway.CatwayType;

import net.minecraft.block.Block;
import net.minecraft.block.BlockSlab;
import net.minecraft.block.material.Material;
import net.minecraft.item.ItemBlock;
import net.minecraft.item.ItemSlab;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class BasicBlocks {
	public static Block vitallium;
	public static BlockSlab vitallium_slab_half;
	public static BlockSlab vitallium_slab_double;
	public static Block vitallium_ore;
	public static Block vitallium_fence;
	public static Block vitallium_fence_gate;
	public static Block strontenium_fence_gate;
	public static Block strontenium_fence;
	public static Block perolit;
	public static Block perolit_ore;
	public static Block perola;
	public static Block perolb;
	public static Block perolc;
	public static Block perold;
	public static Block klingonium_ore;
	public static Block klingonit;
	public static Block klingosit;
	public static Block klingosita;
	public static Block klingositb;
	public static Block klingodur;
	public static Block klingopar;
	public static Block klingonium_screw;
	public static Block klingonium;
	public static Block klingonium0;
	public static Block klingonium1;
	public static Block klingonium2;
	public static Block klingonium3;
	public static Block klingonium_wall0;
	public static Block klingonium_wall1;
	public static Block klingonium_wall2;
	public static Block klingonium_wall3;
	public static Block klingonium_wall4;
	public static Block klingonium_wall5;
	public static Block klingonium_wall6;
	public static Block klingonium_wall7;
	public static Block klingonium_wall8;
	public static Block strontenium;
	public static Block strontecore;
	public static Block strontenium_glass;
	public static Block strontenium_glass_pane;
	public static Block strontenium0;
	public static Block strontenium1;
	public static Block strontenium2;
	public static Block strontenium_ore;
	public static Block strontenita;
	public static Block strontenitb;
	public static Block strontenitc;
	public static Block strontenitd;
	public static Block strontenal;
	public static Block oxygen;
	public static Block strontopal;
	public static Block strontopala;
	public static Block strontopalb;
	public static Block cyberit_Ore;
	public static Block block_cyberol;
	public static BlockSlab space_quartz_slab_half;
	public static BlockSlab space_quartz_slab_double;
	public static Block block_space_quartz;
	public static Block block_space_quartza;
	public static Block block_space_quartz_mfblock;
	public static Block space_quartz_ore;
	public static Block table;
	public static Block table1;
	public static Block chair;
	public static Block speedway;
	public static Block tresor;
	public static Block analyser;
	public static Block solar_panel;
	public static Block satellite_antenna;
	public static Block stand_console;
	public static Block virtual_screen;
	public static Block vitallium_glass;
	public static Block vitallium_glass_pane;
	public static Block quartz_window;
	public static Block quartz_window_pane;
	public static Block block_engine;
	public static Block block_ribbed;
	public static Block ceiling_lamp;
	public static Block kitchen_lamp;
	public static Block light_box;
	public static Block lux;
	public static Block metal_lamp;
	public static Block metal_lamp_lit;
	public static Block wall_lamp;
	public static Block wall_lamp_lit;
	public static Block cellar_lamp;
	public static Block cellar_lamp_lit;
	public static Block pipes_connector;
	public static Block constructor1;
	public static Block constructor2;
	public static Block constructor3;
	public static Block constructor4;
	public static Block constructor5;
	public static Block metal_diagonal;
	public static Block metalframeblock;
	public static Block metal_frame_straight;
	public static Block metal_frame_l;
	public static Block metal_frame_t;
	public static Block metal_frame_x;
	public static Block metal_frame_post;
	public static Block metal_frame_zero;
	public static Block metal_frame_vert;
	public static BlockSlab metal_frame_slab_half;
	public static BlockSlab metal_frame_slab_double;
	public static Block metal_ladder;
	public static Block lever1;
	public static Block lever2;
	public static Block lever3;
	public static Block bed1;
	public static Block wash_basin;
	public static Block cooker;
	public static Block metal_button;
	public static Block concrete_pp;
	public static Block klingonit_pp;
	public static Block klingonit1_pp;
	public static Block klingonit2_pp;
	public static Block vitallium_door;
	public static Block wall_panel;
	public static Block wall_panel1;
	public static Block wall_panel2;
	public static Block wall_panel3;
	public static Block cupboard;
	public static Block cupboard1;
	public static Block cupboard2;
	public static Block cupboard3;
	public static Block cupboard4;
	public static Block cupboard_outer;
	public static Block cupboard_inner;
	public static Block cupboard_microwave;
	public static Block cupboard_lower;
	public static Block cupboard_lower1;
	public static Block cupboard_lower2;
	public static Block cupboard_lower3;
	public static Block cupboard_lower_outer;

	public BasicBlocks() {
		init();
		register();
	}

	private void init() {
		vitallium = new BlockVitallium().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(vitallium, "vitallium");
		vitallium_ore = new BlockSpaceExtendedOre().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(vitallium_ore, "vitallium_ore");
		metalframeblock = new BlockMetalFrame().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(metalframeblock, "metalframeblock");
		klingodur = new BlockKlingodur().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingodur, "klingodur");
		klingonit = new BlockKlingonit().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingonit, "klingonit");
		klingosit = new BlockKlingosit().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingosit, "klingosit");
		klingosita = new BlockKlingosita().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingosita, "klingosita");
		klingositb = new BlockKlingositb().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingositb, "klingositb");
		klingonium_ore = new BlockSpaceExtendedOre().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingonium_ore, "klingonium_ore");
		constructor1 = new BlockConstructor(1).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(constructor1, "constructor1");
		constructor2 = new BlockConstructor(2).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(constructor2, "constructor2");
		constructor3 = new BlockConstructor(3).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(constructor3, "constructor3");
		constructor4 = new BlockConstructor(4).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(constructor4, "constructor4");
		constructor5 = new BlockConstructor(5).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(constructor5, "constructor5");
		strontenium = new BlockStrontenium().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(strontenium, "strontenium");
		strontenium0 = new BlockStrontenium0().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(strontenium0, "strontenium0");
		strontenium1 = new BlockStrontenium0().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(strontenium1, "strontenium1");
		strontenium2 = new BlockStrontenium0().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(strontenium2, "strontenium2");
		strontenium_ore = new BlockSpaceExtendedOre().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(strontenium_ore, "strontenium_ore");
		klingonium = new BlockKlingonium().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingonium, "klingonium");
		klingonium0 = new BlockKlingonium().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingonium0, "klingonium0");
		klingonium1 = new BlockKlingonium().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingonium1, "klingonium1");
		klingonium2 = new BlockKlingonium().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingonium2, "klingonium2");
		klingonium3 = new BlockKlingonium().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingonium3, "klingonium3");
		klingonium_wall0 = new BlockKlingoniumWall().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingonium_wall0, "klingonium_wall0");
		klingonium_wall1 = new BlockKlingoniumWall().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingonium_wall1, "klingonium_wall1");
		klingonium_wall2 = new BlockKlingoniumWall().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingonium_wall2, "klingonium_wall2");
		klingonium_wall3 = new BlockKlingoniumWall().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingonium_wall3, "klingonium_wall3");
		klingonium_wall4 = new BlockKlingoniumWall().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingonium_wall4, "klingonium_wall4");
		klingonium_wall5 = new BlockKlingoniumWall().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingonium_wall5, "klingonium_wall5");
		klingonium_wall6 = new BlockKlingoniumWall().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingonium_wall6, "klingonium_wall6");
		klingonium_wall7 = new BlockKlingoniumWall().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingonium_wall7, "klingonium_wall7");
		klingonium_wall8 = new BlockKlingoniumWall().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingonium_wall8, "klingonium_wall8");
		klingonium_screw = new BlockKlingoniumScrew().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingonium_screw, "klingonium_screw");
		perolit = new BlockPerolit().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(perolit, "perolit");
		perolit_ore = new BlockSpaceExtendedOre().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(perolit_ore, "perolit_ore");
		pipes_connector = new BlockPipesConnector().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(pipes_connector, "pipes_connector");
		strontenita = new BlockStrontenit().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(strontenita, "strontenita");
		strontenitb = new BlockStrontenit().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(strontenitb, "strontenitb");
		strontenitc = new BlockStrontenit().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(strontenitc, "strontenitc");
		strontenitd = new BlockStrontenit().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(strontenitd, "strontenitd");
		strontenal = new BlockStrontenal().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(strontenal, "strontenal");
		oxygen = new BlockOxygen().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(oxygen, "oxygen");
		perola = new BlockPerol().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(perola, "perola");
		perolb = new BlockPerol().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(perolb, "perolb");
		perolc = new BlockPerol().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(perolc, "perolc");
		perold = new BlockPerol().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(perold, "perold");
		table = new BlockTable().setCreativeTab(SpaceExtendedMain.furnitureTab);
		NameUtils.setNames(table, "table");
		table1 = new BlockTable1().setCreativeTab(SpaceExtendedMain.furnitureTab);
		NameUtils.setNames(table1, "table1");
		chair = new BlockChair().setCreativeTab(SpaceExtendedMain.furnitureTab);
		NameUtils.setNames(chair, "chair");
		strontopal = new BlockStrontopal().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(strontopal, "strontopal");
		strontopala = new BlockStrontopal().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(strontopala, "strontopala");
		strontopalb = new BlockStrontopal().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(strontopalb, "strontopalb");
		lux = new BlockLux().setCreativeTab(SpaceExtendedMain.furnitureTab);
		NameUtils.setNames(lux, "lux");
		ceiling_lamp = new BlockCeilingLamp().setCreativeTab(SpaceExtendedMain.furnitureTab);
		NameUtils.setNames(ceiling_lamp, "ceiling_lamp");
		kitchen_lamp = new BlockKitchenLamp().setCreativeTab(SpaceExtendedMain.furnitureTab);
		NameUtils.setNames(kitchen_lamp, "kitchen_lamp");
		speedway = new BlockSpeedWay().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(speedway, "speedway");
		klingopar = new BlockKlingoPar().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(klingopar, "klingopar");
		tresor = new BlockTresor().setCreativeTab(SpaceExtendedMain.furnitureTab);
		NameUtils.setNames(tresor, "tresor");
		strontecore = new BlockStronteCore().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(strontecore, "strontecore");
		strontenium_glass = new BlockStrontenium_Glass(Material.GLASS, false)
				.setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(strontenium_glass, "strontenium_glass");
		strontenium_glass_pane = new BlockStrontenium_Glass_Pane(Material.GLASS, false)
				.setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(strontenium_glass_pane, "strontenium_glass_pane");
		cyberit_Ore = new BlockSpaceExtendedOre().setLightLevel(0.7f).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(cyberit_Ore, "cyberit_ore");
		analyser = new BlockAnalyser().setCreativeTab(SpaceExtendedMain.furnitureTab);
		NameUtils.setNames(analyser, "analyser");
		vitallium_glass = new BlockVitalliumGlass(Material.GLASS, false).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(vitallium_glass, "vitallium_glass");
		vitallium_glass_pane = new BlockVitalliumGlassPane(Material.GLASS, false)
				.setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(vitallium_glass_pane, "vitallium_glass_pane");
		virtual_screen = new BlockVirtualScreen(Material.GLASS, false).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(virtual_screen, "virtual_screen");
		block_space_quartz = new BlockSpaceQuartz().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(block_space_quartz, "block_space_quartz");
		block_space_quartza = new BlockSpaceQuartzA().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(block_space_quartza, "block_space_quartza");
		block_space_quartz_mfblock = new BlockSpaceQuartzMFblock(null).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(block_space_quartz_mfblock, "block_space_quartz_mfblock");
		space_quartz_ore = new BlockSpaceExtendedOre(Material.ROCK).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(space_quartz_ore, "space_quartz_ore");
		solar_panel = new BlockSolarPanel().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(solar_panel, "solar_panel");
		satellite_antenna = new BlockSatelliteAntenna().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(satellite_antenna, "satellite_antenna");
		light_box = new BlockLight_Box().setCreativeTab(SpaceExtendedMain.furnitureTab);
		NameUtils.setNames(light_box, "light_box");
		quartz_window = new BlockQuartzWindow(Material.GLASS, false).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(quartz_window, "quartz_window");
		quartz_window_pane = new BlockQuartzWindowPane(Material.GLASS, false)
				.setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(quartz_window_pane, "quartz_window_pane");
		block_engine = new BlockEngine().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(block_engine, "block_engine");
		block_cyberol = new BlockCyberol().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(block_cyberol, "block_cyberol");
		metal_lamp = new BlockMetalLamp(false).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(metal_lamp, "metal_lamp");
		metal_lamp_lit = new BlockMetalLamp(true);
		NameUtils.setNames(metal_lamp_lit, "metal_lamp_lit");
		metal_frame_straight = new BlockMetalFrameCatway(CatwayType.STRAIGHT)
				.setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(metal_frame_straight, "metal_frame_straight");
		metal_frame_l = new BlockMetalFrameCatway(CatwayType.L).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(metal_frame_l, "metal_frame_l");
		metal_frame_t = new BlockMetalFrameCatway(CatwayType.T).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(metal_frame_t, "metal_frame_t");
		metal_frame_x = new BlockMetalFrameCatway(CatwayType.X).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(metal_frame_x, "metal_frame_x");
		metal_frame_post = new BlockMetalFrameCatway(CatwayType.POST).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(metal_frame_post, "metal_frame_post");
		metal_frame_zero = new BlockMetalFrameCatway(CatwayType.ZERO).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(metal_frame_zero, "metal_frame_zero");
		metal_frame_vert = new BlockMetalFrameVert().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(metal_frame_vert, "metal_frame_vert");
		metal_ladder = new BlockMetalLadder().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(metal_ladder, "metal_ladder");
		vitallium_slab_half = (BlockSlab) new BlockVitalliumSlab.Half().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(vitallium_slab_half, "vitallium_slab_half");
		vitallium_slab_double = new BlockVitalliumSlab.Double();
		NameUtils.setNames(vitallium_slab_double, "vitallium_slab_double");
		space_quartz_slab_half = (BlockSlab) new BlockSpaceQuartzSlab.Half().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(space_quartz_slab_half, "space_quartz_slab_half");
		space_quartz_slab_double = new BlockSpaceQuartzSlab.Double();
		NameUtils.setNames(space_quartz_slab_double, "space_quartz_slab_double");
		metal_frame_slab_half = (BlockSlab) new BlockMetalFrameSlab.Half().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(metal_frame_slab_half, "metal_frame_slab_half");
		metal_frame_slab_double = new BlockMetalFrameSlab.Double();
		NameUtils.setNames(metal_frame_slab_double, "metal_frame_slab_double");
		wall_lamp = new BlockWallLamp(false).setCreativeTab(SpaceExtendedMain.furnitureTab);
		NameUtils.setNames(wall_lamp, "wall_lamp");
		wall_lamp_lit = new BlockWallLamp(true);
		NameUtils.setNames(wall_lamp_lit, "wall_lamp_lit");
		stand_console = new BlockStandConsole().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(stand_console, "stand_console");
		metal_diagonal = new BlockMetalDiagonal().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(metal_diagonal, "metal_diagonal");
		lever1 = new BlockCustomLever();
		NameUtils.setNames(lever1, "lever1");
		lever2 = new BlockCustomLever();
		NameUtils.setNames(lever2, "lever2");
		lever3 = new BlockCustomLever();
		NameUtils.setNames(lever3, "lever3");
		block_ribbed = new BlockRibbed().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(block_ribbed, "block_ribbed");
		cellar_lamp = new BlockCellarLamp(false).setCreativeTab(SpaceExtendedMain.furnitureTab);
		NameUtils.setNames(cellar_lamp, "cellar_lamp");
		cellar_lamp_lit = new BlockCellarLamp(true);
		NameUtils.setNames(cellar_lamp_lit, "cellar_lamp_lit");
		bed1 = new BlockCustomBed();
		NameUtils.setNames(bed1, "bed1");
		wash_basin = new BlockWashBasin().setCreativeTab(SpaceExtendedMain.furnitureTab);
		NameUtils.setNames(wash_basin, "wash_basin");
		cooker = new BlockCooker().setCreativeTab(SpaceExtendedMain.furnitureTab);
		NameUtils.setNames(cooker, "cooker");
		concrete_pp = new BlockCustomPP();
		NameUtils.setNames(concrete_pp, "concrete_pp");
		klingonit_pp = new BlockCustomPP();
		NameUtils.setNames(klingonit_pp, "klingonit_pp");
		klingonit1_pp = new BlockCustomPP();
		NameUtils.setNames(klingonit1_pp, "klingonit1_pp");
		klingonit2_pp = new BlockCustomPP();
		NameUtils.setNames(klingonit2_pp, "klingonit2_pp");
		vitallium_door = new BlockVitalliumDoor().setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(vitallium_door, "vitallium_door");
		metal_button = new BlockMetalButton(false).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(metal_button, "metal_button");
		vitallium_fence = new BlockVitalliumFence(null).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(vitallium_fence, "vitallium_fence");
		vitallium_fence_gate = new BlockVitalliumFenceGate(null).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(vitallium_fence_gate, "vitallium_fence_gate");
		strontenium_fence = new BlockStronteniumFence(null).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(strontenium_fence, "strontenium_fence");
		strontenium_fence_gate = new BlockStronteniumFenceGate(null).setCreativeTab(SpaceExtendedMain.spaceTab);
		NameUtils.setNames(strontenium_fence_gate, "strontenium_fence_gate");
		wall_panel = new BlockCustomWallPanel();
		NameUtils.setNames(wall_panel, "wall_panel");
		wall_panel1 = new BlockCustomWallPanel();
		NameUtils.setNames(wall_panel1, "wall_panel1");
		wall_panel2 = new BlockCustomWallPanel();
		NameUtils.setNames(wall_panel2, "wall_panel2");
		wall_panel3 = new BlockCustomWallPanel();
		NameUtils.setNames(wall_panel3, "wall_panel3");
		cupboard = new BlockCustomCupboard();
		NameUtils.setNames(cupboard, "cupboard");
		cupboard1 = new BlockCustomCupboard();
		NameUtils.setNames(cupboard1, "cupboard1");
		cupboard2 = new BlockCustomCupboard();
		NameUtils.setNames(cupboard2, "cupboard2");
		cupboard3 = new BlockCustomCupboard();
		NameUtils.setNames(cupboard3, "cupboard3");
		cupboard4 = new BlockCustomCupboard();
		NameUtils.setNames(cupboard4, "cupboard4");
		cupboard_microwave = new BlockCustomCupboard();
		NameUtils.setNames(cupboard_microwave, "cupboard_microwave");
		cupboard_outer = new BlockCupboardOuter().setCreativeTab(SpaceExtendedMain.furnitureTab);
		NameUtils.setNames(cupboard_outer, "cupboard_outer");
		cupboard_inner = new BlockCupboardInner().setCreativeTab(SpaceExtendedMain.furnitureTab);
		NameUtils.setNames(cupboard_inner, "cupboard_inner");
		cupboard_lower = new BlockCustomCupboardLower();
		NameUtils.setNames(cupboard_lower, "cupboard_lower");
		cupboard_lower1 = new BlockCustomCupboardLower();
		NameUtils.setNames(cupboard_lower1, "cupboard_lower1");
		cupboard_lower2 = new BlockCustomCupboardLower();
		NameUtils.setNames(cupboard_lower2, "cupboard_lower2");
		cupboard_lower3 = new BlockCustomCupboardLower();
		NameUtils.setNames(cupboard_lower3, "cupboard_lower3");
		cupboard_lower_outer = new BlockCustomCupboardLower();
		NameUtils.setNames(cupboard_lower_outer, "cupboard_lower_outer");
	}

	private void register() {
		registerBlock(vitallium);
		registerSlab(vitallium_slab_half, vitallium_slab_double);
		registerBlock(vitallium_ore);
		registerBlock(vitallium_fence);
		registerBlock(vitallium_fence_gate);
		registerBlock(strontenium_fence);
		registerBlock(strontenium_fence_gate);
		registerBlock(perolit);
		registerBlock(perolit_ore);
		registerBlock(perola);
		registerBlock(perolb);
		registerBlock(perolc);
		registerBlock(perold);
		registerBlock(klingonium_ore);
		registerBlock(klingonit);
		registerBlock(klingosit);
		registerBlock(klingosita);
		registerBlock(klingositb);
		registerBlock(klingodur);
		registerBlock(klingopar);
		registerBlock(klingonium_screw);
		registerBlock(klingonium);
		registerBlock(klingonium0);
		registerBlock(klingonium1);
		registerBlock(klingonium2);
		registerBlock(klingonium3);
		registerBlock(klingonium_wall0);
		registerBlock(klingonium_wall1);
		registerBlock(klingonium_wall2);
		registerBlock(klingonium_wall3);
		registerBlock(klingonium_wall4);
		registerBlock(klingonium_wall5);
		registerBlock(klingonium_wall6);
		registerBlock(klingonium_wall7);
		registerBlock(klingonium_wall8);
		registerBlock(strontenium);
		registerBlock(strontecore);
		registerBlock(strontenium_glass);
		registerBlock(strontenium_glass_pane);
		registerBlock(strontenium0);
		registerBlock(strontenium1);
		registerBlock(strontenium2);
		registerBlock(strontenium_ore);
		registerBlock(strontenita);
		registerBlock(strontenitb);
		registerBlock(strontenitc);
		registerBlock(strontenitd);
		registerBlock(strontenal);
		registerBlock(oxygen);
		registerBlock(strontopal);
		registerBlock(strontopala);
		registerBlock(strontopalb);
		registerBlock(cyberit_Ore);
		registerBlock(block_cyberol);
		registerSlab(space_quartz_slab_half, space_quartz_slab_double);
		registerBlock(block_space_quartz);
		registerBlock(block_space_quartza);
		registerBlock(block_space_quartz_mfblock);
		registerBlock(space_quartz_ore);
		registerBlock(table);
		registerBlock(table1);
		registerBlock(chair);
		registerBlock(speedway);
		registerBlock(tresor);
		registerBlock(analyser);
		registerBlock(solar_panel);
		registerBlock(satellite_antenna);
		registerBlock(stand_console);
		registerBlock(virtual_screen);
		registerBlock(vitallium_glass);
		registerBlock(vitallium_glass_pane);
		registerBlock(quartz_window);
		registerBlock(quartz_window_pane);
		registerBlock(block_engine);
		registerBlock(block_ribbed);
		registerBlock(ceiling_lamp);
		registerBlock(kitchen_lamp);
		registerBlock(light_box);
		registerBlock(lux);
		registerBlock(metal_lamp);
		registerBlock(metal_lamp_lit);
		registerBlock(wall_lamp);
		registerBlock(wall_lamp_lit);
		registerBlock(pipes_connector);
		registerBlock(constructor1);
		registerBlock(constructor2);
		registerBlock(constructor3);
		registerBlock(constructor4);
		registerBlock(constructor5);
		registerBlock(metal_diagonal);
		registerBlock(metalframeblock);
		registerBlock(metal_frame_straight);
		registerBlock(metal_frame_l);
		registerBlock(metal_frame_t);
		registerBlock(metal_frame_x);
		registerBlock(metal_frame_post);
		registerBlock(metal_frame_zero);
		registerBlock(metal_frame_vert);
		registerSlab(metal_frame_slab_half, metal_frame_slab_double);
		registerBlock(metal_ladder);
		registerBlock(lever1);
		registerBlock(lever2);
		registerBlock(lever3);
		registerBlock(cellar_lamp);
		registerBlock(cellar_lamp_lit);
		registerBlockOnly(bed1);
		registerBlock(wash_basin);
		registerBlock(cooker);
		registerBlock(metal_button);
		registerBlock(concrete_pp);
		registerBlock(klingonit_pp);
		registerBlock(klingonit1_pp);
		registerBlock(klingonit2_pp);
		registerBlock(vitallium_door);
		registerBlock(wall_panel);
		registerBlock(wall_panel1);
		registerBlock(wall_panel2);
		registerBlock(wall_panel3);
		registerBlock(cupboard);
		registerBlock(cupboard1);
		registerBlock(cupboard2);
		registerBlock(cupboard3);
		registerBlock(cupboard4);
		registerBlock(cupboard_outer);
		registerBlock(cupboard_inner);
		registerBlock(cupboard_microwave);
		registerBlock(cupboard_lower);
		registerBlock(cupboard_lower1);
		registerBlock(cupboard_lower2);
		registerBlock(cupboard_lower3);
		registerBlock(cupboard_lower_outer);
	}

	private void registerBlock(Block block) {
		GameRegistry.register(block);
		ItemBlock itemblock = new ItemBlock(block);
		itemblock.setUnlocalizedName(block.getUnlocalizedName()).setRegistryName(block.getRegistryName());
		GameRegistry.register(itemblock);
	}

	private void registerBlockOnly(Block block) {
		GameRegistry.register(block);
	}

	private void registerSlab(BlockSlab halfSlab, BlockSlab doubleSlab) {
		GameRegistry.register(halfSlab);
		GameRegistry.register(doubleSlab);

		ItemBlock itemblock = new ItemSlab(halfSlab, halfSlab, doubleSlab);
		itemblock.setUnlocalizedName(halfSlab.getUnlocalizedName()).setRegistryName(halfSlab.getRegistryName());
		GameRegistry.register(itemblock);
	}
}
