package com.space.extended.basicblocks;

import com.space.extended.NameUtils;
import com.space.extended.SpaceExtendedMain;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.item.ItemBlock;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class BasicBlocks {

	public static Block vitallium;
	public static Block vitalliumOre;
	public static Block perolit;
	public static Block perolitOre;
	public static Block metalframeblock;
	public static Block klingonium;
	public static Block klingonit;
	public static Block klingodur;
	public static Block klingopar;
	public static Block klingonium_screw;
	public static Block klingonium0;
	public static Block klingonium1;
	public static Block klingonium2;
	public static Block klingonium3;
	public static Block klingonium_wall6;
	public static Block klingonium_wall7;
	public static Block klingonium_wall8;
	public static Block klingonium_wall4;
	public static Block klingonium_wall3;
	public static Block klingonium_wall5;
	public static Block klingonium_wall0;
	public static Block klingonium_wall1;
	public static Block klingonium_wall2;
	public static Block klingoniumOre;
	public static Block constructor1;
	public static Block constructor2;
	public static Block constructor3;
	public static Block constructor4;
	public static Block constructor5;
	public static Block strontenium;
	public static Block strontenium_glass;
	public static Block strontenium_glass_pane;
	public static Block strontenium0;
	public static Block strontenium1;
	public static Block strontenium2;
	public static Block stronteniumOre;
	public static Block pipes_connector;
	public static Block strontenita;
	public static Block strontenitb;
	public static Block strontenitc;
	public static Block strontenitd;
	public static Block strontenal;
	public static Block strontopal;
	public static Block strontopala;
	public static Block strontopalb;
	public static Block oxygen;
	public static Block perola;
	public static Block perolb;
	public static Block perolc;
	public static Block perold;
	public static Block table;
	public static Block lux;
	public static Block ceiling_lamp;
	public static Block speedway;
	public static Block tresor;
	public static Block strontecore;
	public static Block block_space_quartz;
	public static Block block_space_quartza;
	public static Block block_space_quartz_mfblock;
	public static Block cyberit_Ore;
	public static Block vitallium_glass;
	public static Block vitallium_glass_pane;
	public static Block analyser;
	public static Block virtual_screen;
	public static Block space_quartz_ore;
	public static Block solar_panel;
	public static Block satellite_antenna;
	public static Block light_box;
	public static Block quartz_window;
	public static Block quartz_window_pane;
	public static Block block_engine;
	public static Block block_cyberol;

	public BasicBlocks() {
		init();
		register();

	}

	private void init() {
		vitallium = new BlockVitallium().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(vitallium, "vitallium");
		vitalliumOre = new BlockVitalliumOre().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(vitalliumOre, "vitalliumOre");
		metalframeblock = new BlockMetalFrame().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(metalframeblock, "metalframeblock");
		klingonium = new BlockKlingonium().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(klingonium, "klingonium");
		klingodur = new BlockKlingodur().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(klingodur, "klingodur");
		klingonit = new BlockKlingonit().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(klingonit, "klingonit");
		klingoniumOre = new BlockKlingoniumOre().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(klingoniumOre, "klingoniumOre");
		constructor1 = new BlockConstructor1().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(constructor1, "constructor1");
		constructor2 = new BlockConstructor2().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(constructor2, "constructor2");
		constructor3 = new BlockConstructor3().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(constructor3, "constructor3");
		constructor4 = new BlockConstructor4().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(constructor4, "constructor4");
		constructor5 = new BlockConstructor5().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(constructor5, "constructor5");
		strontenium = new BlockStrontenium().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(strontenium, "strontenium");
		strontenium0 = new BlockStrontenium0().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(strontenium0, "strontenium0");
		strontenium1 = new BlockStrontenium1().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(strontenium1, "strontenium1");
		strontenium2 = new BlockStrontenium2().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(strontenium2, "strontenium2");
		stronteniumOre = new BlockStronteniumOre().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(stronteniumOre, "stronteniumOre");
		klingonium0 = new BlockKlingonium0().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(klingonium0, "klingonium0");
		klingonium1 = new BlockKlingonium1().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(klingonium1, "klingonium1");
		klingonium2 = new BlockKlingonium2().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(klingonium2, "klingonium2");
		klingonium3 = new BlockKlingonium3().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(klingonium3, "klingonium3");
		klingonium_wall0 = new BlockKlingonium_Wall0().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(klingonium_wall0, "klingonium_wall0");
		klingonium_wall1 = new BlockKlingonium_Wall1().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(klingonium_wall1, "klingonium_wall1");
		klingonium_wall2 = new BlockKlingonium_Wall2().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(klingonium_wall2, "klingonium_wall2");
		klingonium_wall3 = new BlockKlingonium_Wall3().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(klingonium_wall3, "klingonium_wall3");
		klingonium_wall4 = new BlockKlingonium_Wall4().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(klingonium_wall4, "klingonium_wall4");
		klingonium_wall5 = new BlockKlingonium_Wall5().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(klingonium_wall5, "klingonium_wall5");
		klingonium_wall6 = new BlockKlingonium_Wall6().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(klingonium_wall6, "klingonium_wall6");
		klingonium_wall7 = new BlockKlingonium_Wall7().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(klingonium_wall7, "klingonium_wall7");
		klingonium_wall8 = new BlockKlingonium_Wall8().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(klingonium_wall8, "klingonium_wall8");
		klingonium_screw = new BlockKlingoniumScrew().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(klingonium_screw, "klingonium_screw");
		perolit = new BlockPerolit().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(perolit, "perolit");
		perolitOre = new BlockPerolitOre().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(perolitOre, "perolitOre");
		pipes_connector = new BlockPipes_Connector().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(pipes_connector, "pipes_connector");
		strontenita = new BlockStrontenitA().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(strontenita, "strontenita");
		strontenitb = new BlockStrontenitB().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(strontenitb, "strontenitb");
		strontenitc = new BlockStrontenitC().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(strontenitc, "strontenitc");
		strontenitd = new BlockStrontenitD().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(strontenitd, "strontenitd");
		strontenal = new BlockStrontenal().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(strontenal, "strontenal");
		oxygen = new BlockOxygen().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(oxygen, "oxygen");
		perola = new BlockPerolA().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(perola, "perola");
		perolb = new BlockPerolB().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(perolb, "perolb");
		perolc = new BlockPerolC().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(perolc, "perolc");
		perold = new BlockPerolD().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(perold, "perold");
		table = new BlockTable().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(table, "table");
		strontopal = new BlockStrontopal().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(strontopal, "strontopal");
		strontopala = new BlockStrontopalA().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(strontopala, "strontopala");
		strontopalb = new BlockStrontopalB().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(strontopalb, "strontopalb");
		lux = new BlockLux().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(lux, "lux");
		ceiling_lamp = new BlockCeiling_Lamp().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(ceiling_lamp, "ceiling_lamp");
		speedway = new BlockSpeedWay().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(speedway, "speedway");
		klingopar = new BlockKlingoPar().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(klingopar, "klingopar");
		tresor = new BlockTresor().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(tresor, "tresor");
		strontecore = new BlockStronteCore().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(strontecore, "strontecore");
		strontenium_glass = new BlockStrontenium_Glass(Material.GLASS, false).setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(strontenium_glass, "strontenium_glass");
		strontenium_glass_pane = new BlockStrontenium_Glass_Pane(Material.GLASS, false)
				.setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(strontenium_glass_pane, "strontenium_glass_pane");
		cyberit_Ore = new BlockCyberit_Ore().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(cyberit_Ore, "cyberit_Ore");
		analyser = new BlockAnalyser().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(analyser, "analyser");
		vitallium_glass = new BlockVitallium_Glass(Material.GLASS, false).setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(vitallium_glass, "vitallium_glass");
		vitallium_glass_pane = new BlockVitallium_Glass_Pane(Material.GLASS, false)
				.setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(vitallium_glass_pane, "vitallium_glass_pane");
		virtual_screen = new BlockVirtual_Screen(Material.GLASS, false).setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(virtual_screen, "virtual_screen");
		block_space_quartz = new Block_Space_Quartz().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(block_space_quartz, "block_space_quartz");
		block_space_quartza = new Block_Space_QuartzA().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(block_space_quartza, "block_space_quartza");
		block_space_quartz_mfblock = new Block_Space_Quartz_MFblock(null).setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(block_space_quartz_mfblock, "block_space_quartz_mfblock");
		space_quartz_ore = new BlockSpace_Quartz_Ore().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(space_quartz_ore, "space_quartz_ore");
		solar_panel = new BlockSolar_Panel().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(solar_panel, "solar_panel");
		satellite_antenna = new BlockSatellite_Antenna().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(satellite_antenna, "satellite_antenna");
		light_box = new BlockLight_Box().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(light_box, "light_box");
		quartz_window = new BlockQuartz_Window(Material.GLASS, false).setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(quartz_window, "quartz_window");
		quartz_window_pane = new BlockQuartz_Window_Pane(Material.GLASS, false).setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(quartz_window_pane, "quartz_window_pane");
		block_engine = new Block_Engine().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(block_engine, "block_engine");
		block_cyberol = new Block_Cyberol().setCreativeTab(SpaceExtendedMain.tab);
		NameUtils.setNames(block_cyberol, "block_cyberol");

	}

	private void register() {
		registerBlock(vitallium);
		registerBlock(vitalliumOre);
		registerBlock(metalframeblock);
		registerBlock(klingonium);
		registerBlock(klingodur);
		registerBlock(klingonit);
		registerBlock(klingonium0);
		registerBlock(klingonium1);
		registerBlock(klingonium2);
		registerBlock(klingonium3);
		registerBlock(klingoniumOre);
		registerBlock(constructor1);
		registerBlock(constructor2);
		registerBlock(constructor3);
		registerBlock(constructor4);
		registerBlock(constructor5);
		registerBlock(strontenium);
		registerBlock(strontenium0);
		registerBlock(strontenium1);
		registerBlock(strontenium2);
		registerBlock(stronteniumOre);
		registerBlock(klingonium_wall0);
		registerBlock(klingonium_wall1);
		registerBlock(klingonium_wall2);
		registerBlock(klingonium_wall3);
		registerBlock(klingonium_wall4);
		registerBlock(klingonium_wall5);
		registerBlock(klingonium_wall6);
		registerBlock(klingonium_wall7);
		registerBlock(klingonium_wall8);
		registerBlock(klingonium_screw);
		registerBlock(perolit);
		registerBlock(perolitOre);
		registerBlock(pipes_connector);
		registerBlock(strontenita);
		registerBlock(strontenitb);
		registerBlock(strontenitc);
		registerBlock(strontenitd);
		registerBlock(strontenal);
		registerBlock(oxygen);
		registerBlock(perola);
		registerBlock(perolb);
		registerBlock(perolc);
		registerBlock(perold);
		registerBlock(table);
		registerBlock(strontopal);
		registerBlock(strontopala);
		registerBlock(strontopalb);
		registerBlock(lux);
		registerBlock(ceiling_lamp);
		registerBlock(speedway);
		registerBlock(klingopar);
		registerBlock(tresor);
		registerBlock(strontecore);
		registerBlock(cyberit_Ore);
		registerBlock(vitallium_glass);
		registerBlock(vitallium_glass_pane);
		registerBlock(strontenium_glass);
		registerBlock(strontenium_glass_pane);
		registerBlock(analyser);
		registerBlock(virtual_screen);
		registerBlock(block_space_quartz);
		registerBlock(block_space_quartza);
		registerBlock(block_space_quartz_mfblock);
		registerBlock(space_quartz_ore);
		registerBlock(solar_panel);
		registerBlock(satellite_antenna);
		registerBlock(light_box);
		registerBlock(quartz_window);
		registerBlock(quartz_window_pane);
		registerBlock(block_engine);
		registerBlock(block_cyberol);

	}

	private void registerBlock(Block block) {
		GameRegistry.register(block);
		ItemBlock itemblock = new ItemBlock(block);
		itemblock.setUnlocalizedName(block.getUnlocalizedName()).setRegistryName(block.getRegistryName());
		GameRegistry.register(itemblock);
	}

}
